services:
  # ---------- Web API ----------
  - type: web
    name: editdna-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY <-- add
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET
        sync: false

  # ---------- Background Worker (RQ) ----------
  - type: worker
    name: editdna-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: rq worker -u $REDIS_URL default
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY    # <-- add
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
