"""Real ffmpeg/ffprobe-backed PostRenderWatchListenQC media checks (D-028).

Every fixture below is SYNTHETIC media generated by ffmpeg itself (lavfi
sources: sine tones, testsrc/color frames, aevalsrc constants) -- no
Video00 media, no waiting for a real render, exactly as the canonical
directive requires ("create synthetic/generated media fixtures where
possible... do not wait for Video00 to test basic media-QC behavior").

Skipped automatically (not failed) if `ffmpeg` is not on PATH -- a
robustness guard for an unusual runner image, not a way to avoid ever
running these for real; this session confirmed ffmpeg/ffprobe install
cleanly on the standard CI (ubuntu-latest) image.
"""
import shutil
import subprocess

import pytest

from cutsell_worker.post_render_media_qc import (
    BoundedPhysicalRepairResult,
    check_accidental_silence,
    check_audio_discontinuity_at_boundaries,
    check_dead_black_frames,
    check_frozen_frames,
    probe_decode_integrity,
    run_bounded_physical_repair_loop,
    run_post_render_media_qc,
)
from cutsell_worker.post_render_watch_listen_qc import (
    ABRUPT_AUDIO_DISCONTINUITY,
    DEAD_BLACK_FRAME,
    DECODE_EXPORT_INTEGRITY,
    FROZEN_OR_REPEATED_FRAME,
    LINGERING_ACCIDENTAL_SILENCE,
    STRUCTURAL_DUPLICATE_SEGMENT,
    check_no_duplicate_render_segments,
    is_physical_finding_kind,
)

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not available on this runner")


def _ffmpeg(args):
    subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", *args], check=True)


@pytest.fixture(scope="module")
def media_dir(tmp_path_factory):
    return tmp_path_factory.mktemp("post_render_media_qc")


@pytest.fixture(scope="module")
def clean_av(media_dir):
    path = str(media_dir / "clean_av.mp4")
    _ffmpeg([
        "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
        "-f", "lavfi", "-i", "testsrc=size=64x64:rate=25:duration=2",
        "-c:v", "libx264", "-c:a", "aac", "-shortest", "-y", path,
    ])
    return path


@pytest.fixture(scope="module")
def corrupt_media(media_dir, clean_av):
    path = str(media_dir / "corrupt.mp4")
    with open(clean_av, "rb") as source, open(path, "wb") as dest:
        dest.write(source.read(5000))
    return path


@pytest.fixture(scope="module")
def silence_audio(media_dir):
    # sine(1s) + true silence(2s) + sine(1s) -- a 2s accidental gap.
    path = str(media_dir / "silence.wav")
    _ffmpeg([
        "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
        "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono:duration=2",
        "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
        "-filter_complex", "[0:a][1:a][2:a]concat=n=3:v=0:a=1[a]",
        "-map", "[a]", "-y", path,
    ])
    return path


@pytest.fixture(scope="module")
def continuous_audio(media_dir):
    path = str(media_dir / "continuous.wav")
    _ffmpeg(["-f", "lavfi", "-i", "sine=frequency=440:duration=3", "-y", path])
    return path


@pytest.fixture(scope="module")
def freeze_video(media_dir):
    # testsrc(1s) + a still frame held for 1s + testsrc(1s).
    path = str(media_dir / "freeze.mp4")
    _ffmpeg([
        "-f", "lavfi", "-i", "testsrc=size=64x64:rate=25:duration=1",
        "-f", "lavfi", "-i", "color=c=red:s=64x64:rate=25:duration=1",
        "-f", "lavfi", "-i", "testsrc=size=64x64:rate=25:duration=1",
        "-filter_complex", "[0:v][1:v][2:v]concat=n=3:v=1:a=0[v]",
        "-map", "[v]", "-c:v", "libx264", "-y", path,
    ])
    return path


@pytest.fixture(scope="module")
def black_video(media_dir):
    path = str(media_dir / "black.mp4")
    _ffmpeg([
        "-f", "lavfi", "-i", "testsrc=size=64x64:rate=25:duration=1",
        "-f", "lavfi", "-i", "color=c=black:s=64x64:rate=25:duration=1",
        "-f", "lavfi", "-i", "testsrc=size=64x64:rate=25:duration=1",
        "-filter_complex", "[0:v][1:v][2:v]concat=n=3:v=1:a=0[v]",
        "-map", "[v]", "-c:v", "libx264", "-y", path,
    ])
    return path


@pytest.fixture(scope="module")
def continuous_video(media_dir):
    path = str(media_dir / "continuous_video.mp4")
    _ffmpeg([
        "-f", "lavfi", "-i", "testsrc=size=64x64:rate=25:duration=2",
        "-c:v", "libx264", "-y", path,
    ])
    return path


@pytest.fixture(scope="module")
def discontinuity_audio(media_dir):
    # A hard instantaneous jump from +0.8 to -0.8 amplitude at t=1.0 --
    # the actual acoustic signature of a bad edit-point splice.
    path = str(media_dir / "jump.wav")
    _ffmpeg([
        "-f", "lavfi", "-i", "aevalsrc=0.8:d=1:s=22050",
        "-f", "lavfi", "-i", "aevalsrc=-0.8:d=1:s=22050",
        "-filter_complex", "[0:a][1:a]concat=n=2:v=0:a=1[a]",
        "-map", "[a]", "-y", path,
    ])
    return path


# ---------------------------------------------------------------------------
# DECODE_EXPORT_INTEGRITY -- probe_decode_integrity
# ---------------------------------------------------------------------------

def test_clean_media_passes_decode_integrity(clean_av):
    result = probe_decode_integrity(clean_av)
    assert result.status == "PASS"
    assert result.findings == ()


def test_truncated_media_fails_decode_integrity(corrupt_media):
    result = probe_decode_integrity(corrupt_media)
    assert result.status == "FAIL"
    assert result.findings[0].kind == DECODE_EXPORT_INTEGRITY
    assert result.findings[0].routes_to == "BoundaryEngine"


# ---------------------------------------------------------------------------
# LINGERING_ACCIDENTAL_SILENCE -- check_accidental_silence
# ---------------------------------------------------------------------------

def test_excessive_accidental_silence_is_detected(silence_audio):
    result = check_accidental_silence(silence_audio, max_allowed_silence_sec=1.0)
    assert result.status == "FAIL"
    assert result.findings[0].kind == LINGERING_ACCIDENTAL_SILENCE
    assert result.findings[0].detail["duration_sec"] >= 1.0


def test_intentional_protected_pause_is_preserved(silence_audio):
    # The same ~2s silence, but the caller marks [0.9, 3.1] as an
    # editorially intentional pause -- must not be flagged.
    result = check_accidental_silence(
        silence_audio, max_allowed_silence_sec=1.0, protected_pause_windows=[(0.9, 3.1)],
    )
    assert result.status == "PASS"
    assert result.findings == ()


def test_continuous_audio_with_no_gap_passes_silence_check(continuous_audio):
    result = check_accidental_silence(continuous_audio, max_allowed_silence_sec=1.0)
    assert result.status == "PASS"


# ---------------------------------------------------------------------------
# FROZEN_OR_REPEATED_FRAME / DEAD_BLACK_FRAME
# ---------------------------------------------------------------------------

def test_frozen_stretch_is_detected(freeze_video):
    result = check_frozen_frames(freeze_video, min_freeze_sec=0.3)
    assert result.status == "FAIL"
    assert result.findings[0].kind == FROZEN_OR_REPEATED_FRAME
    assert result.findings[0].routes_to == "BoundaryEngine"


def test_continuously_changing_video_has_no_frozen_frames(continuous_video):
    result = check_frozen_frames(continuous_video, min_freeze_sec=0.3)
    assert result.status == "PASS"


def test_dead_black_stretch_is_detected(black_video):
    result = check_dead_black_frames(black_video, min_black_sec=0.3)
    assert result.status == "FAIL"
    assert result.findings[0].kind == DEAD_BLACK_FRAME


def test_normal_video_has_no_black_frames(continuous_video):
    result = check_dead_black_frames(continuous_video, min_black_sec=0.3)
    assert result.status == "PASS"


# ---------------------------------------------------------------------------
# ABRUPT_AUDIO_DISCONTINUITY
# ---------------------------------------------------------------------------

def test_hard_amplitude_jump_at_a_splice_point_is_detected(discontinuity_audio):
    result = check_audio_discontinuity_at_boundaries(discontinuity_audio, [1.0])
    assert result.status == "FAIL"
    assert result.findings[0].kind == ABRUPT_AUDIO_DISCONTINUITY
    assert result.findings[0].routes_to == "BoundaryEngine"


def test_a_clean_boundary_inside_continuous_audio_passes(continuous_audio):
    result = check_audio_discontinuity_at_boundaries(continuous_audio, [1.5])
    assert result.status == "PASS"


# ---------------------------------------------------------------------------
# Orchestrator + authority invariant
# ---------------------------------------------------------------------------

def test_run_post_render_media_qc_passes_on_clean_media(clean_av):
    result = run_post_render_media_qc(clean_av)
    assert result.status == "PASS"


def test_run_post_render_media_qc_short_circuits_on_decode_failure(corrupt_media):
    result = run_post_render_media_qc(corrupt_media)
    assert result.status == "FAIL"
    assert [f.kind for f in result.findings] == [DECODE_EXPORT_INTEGRITY]


def test_every_finding_run_post_render_media_qc_can_emit_is_physical(freeze_video):
    result = run_post_render_media_qc(freeze_video, min_freeze_sec=0.3)
    assert result.status == "FAIL"
    assert all(is_physical_finding_kind(f.kind) for f in result.findings)


# ---------------------------------------------------------------------------
# STRUCTURAL_DUPLICATE_SEGMENT -- check_no_duplicate_render_segments
# ---------------------------------------------------------------------------

class _FakeSegment:
    def __init__(self, clip_id, source_asset_id="src", start=0.0, end=1.0):
        self.clip_id = clip_id
        self.source_asset_id = source_asset_id
        self.start = start
        self.end = end


def test_no_duplicate_segments_passes_with_distinct_clip_ids():
    result = check_no_duplicate_render_segments([_FakeSegment("a"), _FakeSegment("b")])
    assert result.status == "PASS"


def test_duplicate_clip_id_across_two_segments_is_detected():
    result = check_no_duplicate_render_segments([
        _FakeSegment("a", start=0.0, end=1.0), _FakeSegment("a", start=5.0, end=6.0),
    ])
    assert result.status == "FAIL"
    assert result.findings[0].kind == STRUCTURAL_DUPLICATE_SEGMENT
    assert result.findings[0].detail["occurrence_count"] == 2


# ---------------------------------------------------------------------------
# run_bounded_physical_repair_loop
# ---------------------------------------------------------------------------

def test_bounded_physical_repair_loop_passes_when_a_later_attempt_is_clean(clean_av, corrupt_media):
    calls = []

    def render_attempt(attempt_index):
        calls.append(attempt_index)
        return corrupt_media if attempt_index == 0 else clean_av

    result = run_bounded_physical_repair_loop(render_attempt, max_attempts=3)

    assert isinstance(result, BoundedPhysicalRepairResult)
    assert result.status == "PASS"
    assert len(result.attempts) == 2
    assert result.attempts[0].repaired is False
    assert result.attempts[1].repaired is True
    assert calls == [0, 1]


def test_bounded_physical_repair_loop_terminates_as_needs_human_review(corrupt_media):
    result = run_bounded_physical_repair_loop(lambda attempt_index: corrupt_media, max_attempts=3)

    assert result.status == "NEEDS_HUMAN_REVIEW"
    assert len(result.attempts) == 3  # bounded -- never spins past max_attempts
    assert all(a.repaired is False for a in result.attempts)


def test_bounded_physical_repair_loop_never_claims_pass_while_a_finding_remains(corrupt_media):
    result = run_bounded_physical_repair_loop(lambda attempt_index: corrupt_media, max_attempts=2)
    assert result.status != "PASS"


def test_bounded_physical_repair_loop_refuses_a_non_physical_finding_kind(clean_av):
    from cutsell_worker.post_render_watch_listen_qc import PostRenderFinding, PostRenderQCResult

    def fake_semantic_qc(_media_path):
        return PostRenderQCResult(
            status="FAIL",
            findings=(PostRenderFinding(
                kind="DUPLICATE_IDEA", start=0.0, end=0.0, detail={}, routes_to="BestTakeResolver",
            ),),
        )

    with pytest.raises(ValueError):
        run_bounded_physical_repair_loop(lambda attempt_index: clean_av, qc_check=fake_semantic_qc)
