"""CutSell clean worker package.

Mobile-first Flow B engine. Modules are intentionally small and communicate
through versioned typed contracts defined in ``cutsell_worker.contracts``.
"""

from .commercial_observability import initialize_observability
from .clean_cut_retry import install_clean_cut_contract_recovery
from .recording_process_context import install_recording_process_context_cleanup
from .recording_suffix_trim import install_visual_self_critique_suffix_trim
from .dangling_delivery import install_dangling_delivery_cleanup
from .internal_self_correction import install_internal_self_correction_trim
from .recording_breaks import install_recording_break_cleanup
from .restart_questions import install_short_restart_question_cleanup
from .frustrated_restart import install_soft_frustration_restart_cleanup
from .micro_restart_cleanup import install_micro_restart_cleanup
from .product_handling_failure import install_product_handling_failure_cleanup
from .micro_self_talk import install_micro_self_talk_cleanup
from .orphan_retry_cleanup import install_orphan_retry_cleanup
from .incomplete_retry_suffix import install_incomplete_retry_suffix_cleanup
from .interstitial_retry_debris import install_interstitial_retry_debris_cleanup
from .trailing_retry_restart import install_trailing_retry_restart_trim
from .local_retry_grouping import install_local_retry_grouping

install_clean_cut_contract_recovery()
install_recording_process_context_cleanup()
install_visual_self_critique_suffix_trim()
install_dangling_delivery_cleanup()
install_internal_self_correction_trim()
install_recording_break_cleanup()
install_short_restart_question_cleanup()
install_soft_frustration_restart_cleanup()
install_micro_restart_cleanup()
install_product_handling_failure_cleanup()
install_micro_self_talk_cleanup()
install_orphan_retry_cleanup()
install_incomplete_retry_suffix_cleanup()
install_interstitial_retry_debris_cleanup()
install_trailing_retry_restart_trim()
install_local_retry_grouping()

__version__ = "0.1.0"
OBSERVABILITY_STATUS = initialize_observability(service="cutsell-worker")
