name: Deploy to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy on VM
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} <<'EOF'
          set -euo pipefail

          cd ~/editdna
          git fetch --all
          git reset --hard origin/main

          # reload env + restart services
          sudo systemctl daemon-reexec
          sudo systemctl restart editdna-api
          sudo systemctl restart editdna-worker

          # show status
          systemctl --no-pager status editdna-api
          systemctl --no-pager status editdna-worker
          EOF
