name: Deploy EditDNA API + Worker to VM

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/deploy.yml"
  workflow_dispatch: {}

concurrency:
  group: deploy-vm
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}

    steps:
      - name: Prepare SSH key
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: SSH into VM and deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 ${VM_USER}@${VM_HOST} bash -s <<'EOF'
          set -Eeuo pipefail

          echo "== Pulling latest code =="
          cd ~/editdna || { echo "editdna repo not found"; exit 1; }
          git fetch --all
          git reset --hard origin/main

          echo "== Installing requirements =="
          . .venv/bin/activate
          pip install -r requirements.txt --quiet

          echo "== Restarting services =="
          sudo systemctl daemon-reload
          sudo systemctl restart editdna-api
          sudo systemctl restart editdna-worker

          echo "== Checking health =="
          sleep 5
          curl -fs http://localhost:5000/health | jq .
          EOF
