name: Deploy to VM (auto-sync worker)

on:
  push:
    branches: [ main ]
    paths:
      - "jobs.py"
      - "tasks.py"
      - "app.py"
      - "start_worker.sh"
      - "requirements.txt"
      - "Dockerfile.worker"
      - "render.yaml"
      - ".github/workflows/deploy-vm.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH → run deploy script on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}        # e.g. 38.224.253.78
          username: ${{ secrets.VM_USER }}    # e.g. user
          key: ${{ secrets.VM_SSH_KEY }}      # your private key contents
          port: ${{ secrets.VM_SSH_PORT || 22 }}
          script: |
            bash ~/deploy_editdna.sh
