name: 💤 RunPod Autoscaler (Idle Reaper)

on:
  schedule:
    - cron: "*/15 * * * *"  # runs every 15 minutes
  workflow_dispatch:

jobs:
  stop_idle_pods:
    runs-on: ubuntu-latest
    steps:
      - name: Stop idle pods on RunPod
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          RUNPOD_TEMPLATE_ID: ${{ secrets.RUNPOD_TEMPLATE_ID }}
        run: |
          echo "Checking for idle pods..."
          curl -s -X GET "https://api.runpod.io/graphql" \
            -H "Authorization: Bearer $RUNPOD_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"query":"{ pods(templateId:\"'$RUNPOD_TEMPLATE_ID'\"){id,name,desiredStatus,uptimeInSeconds}}"}' > pods.json

          cat pods.json
          IDS=$(jq -r '.data.pods[] | select(.desiredStatus == "RUNNING" and .uptimeInSeconds > 3600) | .id' pods.json)
          
          if [ -z "$IDS" ]; then
            echo "✅ No idle pods found."
          else
            echo "⚠️ Stopping idle pods..."
            for id in $IDS; do
              curl -s -X POST "https://api.runpod.io/graphql" \
                -H "Authorization: Bearer $RUNPOD_API_KEY" \
                -H "Content-Type: application/json" \
                -d '{"query":"mutation{podStop(input:{podId:\"'$id'\"}){id}}"}'
              echo "🛑 Pod $id stopped."
            done
          fi
