 name: Build & Push Worker
on:
  push:
    branches: [main]
    paths:
      - "Dockerfile.worker"
      - "tasks.py"
      - "jobs.py"
      - "s3_utils.py"
      - "requirements.txt"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push worker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/editdna-worker:prod
