name: Build & Push RunPod Worker Image
on:
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "Dockerfile.worker"
      - "requirements.txt"
      - "start_worker.sh"
      - ".github/workflows/worker-build.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
    
       IMAGE: ghcr.io/automatedretailservices/editdna-worker:latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (Dockerfile.worker)
        run: docker build -t $IMAGE -f Dockerfile.worker .

      - name: Push image
        run: docker push $IMAGE
